### ISSUE TITLE
BetterC Mallocator

### ISSUE THREAD

**Issue by Zardoz89** [submada/basic-string#1]
You have plans to release your internal BetterC compatible Mallocator ? (https://github.com/submada/basic_string/blob/main/src/basic_string/package.d#L2660)

Could be very useful to another BetterC and @nogc libraries

**Comment by submada** [comment]
No, but betterC Mallocator is a copy of https://github.com/dlang/phobos/blob/master/std/experimental/allocator/mallocator.d#L13 where all methods are static instead of shared. Maybe final (non experimental) version of Mallocator in phobos will have static method or some version of beterC mallcoator will be there.
